server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: database-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
      port: ${DATABASE_PORT:27017}

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
