name: Pull Request Opened

on: # trigger conditions
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    uses: vti-do2402/cicd-core/.github/workflows/ci.yml@feature/actions
    with:
      runs_on: ${{ vars.RUNS_ON }}
      java_version: ${{ vars.JAVA_VERSION }}
      distribution: ${{ vars.JAVA_DISTRIBUTION }}
      github_token: ${{ vars.GITHUB_TOKEN }}
      default_bump: ${{ vars.VERSION_BUMP_TYPE }}
      skip_lint: true
