name: Pull Request Opened

on: # trigger conditions
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    uses: vti-do2402/cicd-core/.github/workflows/maven-spring-ci.yml@dev
    with:
      runs-on: ${{ vars.RUNS_ON }}
      distribution: ${{ vars.JAVA_DISTRIBUTION }}
      java-version: ${{ vars.JAVA_VERSION }}
