name: Pull Request Opened

on: # trigger conditions
  pull_request:
    types: [opened, synchronize, reopened] # Optionally, trigger on pull requests too

jobs:
  build-and-test:
    uses: vti-do2402/cicd-core/.github/workflows/maven-spring-ci.yml@feat/workflow-templates
    with:
      runs-on: ubuntu-latest
