name: Pull Request Opened

on: # trigger conditions
  pull_request:
    branches: [master, dev]
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    uses: vti-do2402/cicd-core/.github/workflows/maven-spring-ci.yml@main
    with:
      runs-on: ubuntu-latest
      distribution: temurin
