name: Pull Request Opened

on: # trigger conditions
  pull_request:
    branches:
      - main
      # - dev
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    name: Test, Analyze and Build
    uses: vti-do2402/cicd-core/.github/workflows/ci-maven.yml@feat/actions
    with:
      runs_on: ${{ vars.RUNS_ON }}
      distribution: ${{ vars.JAVA_DISTRIBUTION }}
      java_version: ${{ vars.JAVA_VERSION }}
      skip_lint: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
