name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"

  tag:
    uses: mathieudutour/github-tag-action@v6.2
    with:
      github_token: ${{ github.token }}
      default_bump: patch
      dry_run: true
