name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  tag:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Calculate or Create Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ github.token }}
          dry_run: true

      - name: ls
        run: |
          ls -la
