name: Build

on:
  push:
    branches:
      - test/cicd

jobs:
  update-k8s:
    name: Update Kubernetes Manifest
    uses: vti-do2402/cicd-core/.github/workflows/update-k8s.yml@feat/k8s-manifest
    with:
      service: database-service
      image: test-image
      runs_on: ubuntu-latest
