name: Build

on:
  push:
    branches:
      - test/cicd

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: vti-do2402/cicd-core/.github/actions/ci/maven/action.yml@feat/update-k8s
        with:
          java_version: 17
          distribution: corretto
          skip_lint: false
