name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  ci:
    name: CI Something
    uses: vti-do2402/cicd-core/.github/workflows/ci.yml@feature/actions
    with:
      runs_on: ${{ vars.RUNS_ON }}
      java_version: ${{ vars.JAVA_VERSION }}
      distribution: ${{ vars.JAVA_DISTRIBUTION }}
      github_token: ${{ github.token }}
      default_bump: ${{ vars.VERSION_BUMP_TYPE }}
      skip_lint: true
