name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  test-deploy:
    uses: vti-do2402/cicd-core/.github/workflows/deploy-ecr.yml@feat/actions
    with:
      runs_on: ${{ vars.RUNS_ON }}
      environment: ${{ vars.ENVIRONMENT }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      image_tag: ${{ github.run_number }}
      aws_account_id: "257120632758"
      aws_region: ${{ vars.AWS_REGION }}
      github_token: ${{ github.token }}
