name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    steps:
      - uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ github.token }}
          default_bump: patch
          dry_run: true

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
