name: Test Approval

on:
  push:
    branches: [feat/ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"

  approval:
    needs: test
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval"

  next-steps:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - run: echo "Next Steps"
