name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  update-k8s:
    name: Update Kubernetes
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout cicd-core
        uses: actions/checkout@v4
        with:
          repository: vti-do2402/cicd-core
          token: ${{ github.token }}
          path: cicd-core

      - name: Update k8s manifest
        run: |
          echo "Current directory: $(pwd)"
          echo "Image tag: yeah"
          sed -i 's/image: .*/image: yeah/' kubernetes/deployment.yml
