name: Test Approval

on:
  push:
    branches: [test/cicd]
env:
  CICD_REPO: vti-do2402/cicd-core
  CICD_VERSION: feat/actions
jobs:
  ci:
    name: CI
    uses: ${{ env.CICD_REPO }}/.github/workflows/ci.yml@${{ env.CICD_VERSION }}
    with:
      runs_on: ${{ vars.RUNS_ON }}
      java_version: ${{ vars.JAVA_VERSION }}
      distribution: ${{ vars.JAVA_DISTRIBUTION }}
      github_token: ${{ github.token }}
      default_bump: ${{ vars.VERSION_BUMP_TYPE }}
      skip_lint: true
