name: Test Approval

on:
  push:
    branches: [test/cicd]

jobs:
  deploy-ecr:
    name: Deploy to Amazon ECR
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for Sonar analysis

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build, Tag, and Push Docker Image to ECR
        shell: bash
        env:
          REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: test
          DOCKERFILE_PATH: Dockerfile
          DOCKER_BUILD_DIRECTORY: .
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_PATH $DOCKER_BUILD_DIRECTORY
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "Image tag: $IMAGE_TAG"
          echo "Push image to ECR: $REGISTRY/$REPOSITORY:$IMAGE_TAG"
